// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Default [FirebaseOptions] for use with your Firebase apps.
//
// Example:
//```dart
// import 'firebase_options.dart';
// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz7MYMW46N4m-qimG0eWnxRW8BzWTbP_Y',
    appId: '1:783894820741:web:d4f73e822dfef8858176ec',
    messagingSenderId: '783894820741',
    projectId: 'nenemotions',
    authDomain: 'nenemotions.firebaseapp.com',
    databaseURL: 'https://nenemotions-default-rtdb.firebaseio.com',
    storageBucket: 'nenemotions.appspot.com',
    measurementId: 'G-50RQNLPQD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy2CcplRv501JPcpIXh5p8zaVd3ATfPLQ',
    appId: '1:783894820741:android:fb7c135844d07fdf8176ec',
    messagingSenderId: '783894820741',
    projectId: 'nenemotions',
    databaseURL: 'https://nenemotions-default-rtdb.firebaseio.com',
    storageBucket: 'nenemotions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWpzrW1hFSDqBlSr4wkgfqcsSKy1z8Odg',
    appId: '1:783894820741:ios:1478cfc0a66109ab8176ec',
    messagingSenderId: '783894820741',
    projectId: 'nenemotions',
    databaseURL: 'https://nenemotions-default-rtdb.firebaseio.com',
    storageBucket: 'nenemotions.appspot.com',
    iosClientId:
        '783894820741-e2v0l68td364p1n3cfd6bomvjt9ra7j4.apps.googleusercontent.com',
    iosBundleId: 'com.example.motionNene',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWpzrW1hFSDqBlSr4wkgfqcsSKy1z8Odg',
    appId: '1:783894820741:ios:1478cfc0a66109ab8176ec',
    messagingSenderId: '783894820741',
    projectId: 'nenemotions',
    databaseURL: 'https://nenemotions-default-rtdb.firebaseio.com',
    storageBucket: 'nenemotions.appspot.com',
    iosClientId:
        '783894820741-e2v0l68td364p1n3cfd6bomvjt9ra7j4.apps.googleusercontent.com',
    iosBundleId: 'com.example.motionNene',
  );
}
